# Generated by Django 4.1.3 on 2022-12-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.EmailField(default='xyz@gmail.com', max_length=254)),
                ('wheat', models.IntegerField()),
                ('rice', models.IntegerField()),
                ('milk', models.IntegerField()),
                ('fruits', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('reciever', models.EmailField(default='xyz@gmail.com', max_length=254)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
